name = "backend"
compatibility_date = "2024-08-16"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODM0ZDFlOGEtZjI2NS00OGUwLWJhYjEtMTA4MzA2M2YzZDI2IiwidGVuYW50X2lkIjoiOGU3ZDk3MDQ5MjQ4M2FhNjI3NTI1MjVhMzcyNTI5MTQzYWNhNTY4ZjY3M2M3OTAwNzlmNDRiMWI5MjVmOTg5NSIsImludGVybmFsX3NlY3JldCI6IjlhMTg0ZjRmLTA3OGItNDlkMi04NWZkLTk0ZGIzNzViOGY3YSJ9.cBXoyHbgFbYVKr_9v5vgtx-3KyZBkWSnRLYM_xF_6N0"
JWT_SECRET ="secretPassword"

# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"